package model;

import java.io.Serializable;

public class Password implements Serializable{
    private String platform; //this field represents the platform which the password is associated to
    private int autoGenerated; // 0 = no , 1 = yes
    private int length; // this field contains the length of the password
    private int typeOfLetters; // 0 = lowercase only, 1 = uppercase only, 2 = both
    private int containsDigits; // 0 = no , 1 = yes
    private int containsSymbols; // 0 = no , 1 = yes
    private String password; // this field represents the password itself

    //password constructor
    public Password(String platform, int autoGenerated, int length, int typeOfLetters, int containsDigits, int containsSymbols, String password){
        this.platform = platform;
        this.autoGenerated = autoGenerated;
        this.length = length;
        this.typeOfLetters = typeOfLetters;
        this.containsDigits = containsDigits;
        this.containsSymbols = containsSymbols;
        this.password = password;
    }

    //platform field getters and setters
    public String getPlatform(){
        return this.platform;
    }
    public void setPlatform(String platform){
        this.platform = platform;
    }

    //autoGenerated field getters and setters
    public int getAutoGenerated(){
        return this.autoGenerated;
    }
    public void setAutoGenerated(int autoGenerated){
        this.autoGenerated = autoGenerated;
    }
    
    //length field getters and setters
    public int getLength(){
        return this.length;
    }
    public void setLength(int length){
        this.length = length;
    }
    
    //typeOfLetters field getters and setters
    public int getTypeOfLetters(){
        return this.typeOfLetters;
    }
    public void setTypeOfLetters(int typeOfLetters){
        this.typeOfLetters = typeOfLetters;
    }
    
    //containsDigits field getters and setters
    public int getContainsDigits(){
        return this.containsDigits;
    }
    public void setContainsDigits(int containsDigits){
        this.containsDigits = containsDigits;
    }
    
    //containsSymbols field getters and setters
    public int getContainsSymbols(){
        return this.containsSymbols;
    }
    public void setContainsSymbols(int containsSymbols){
        this.containsSymbols = containsSymbols;
    }
    
    //password field getters and setters
    public String getPassword(){
        return this.password;
    }
    public void setPassword(String password){
        this.password = password;
    }

    @Override
    public String toString(){
        return "Platform : "+ this.platform +", Password : "+ this.password + ", length : "+ this.length;
    }
}
